services:
  binance_aggregator:
    build: .
    
    # image: ghcr.io/GrayIoda/binance_aggregator_env:latest

    container_name: binance_aggregator_env
    stdin_open: true
    tty: true
    
    volumes:
      - .:/app
      - /app/build
    working_dir: /app
